[menu]
background                = "#171322"
background-alpha          = 0.85
text                      = "#e5d3cc"
border                    = "hyprland.active-border-foreground"
border-alpha              = 1.0
scrim                     = "#0a0810"
scrim-alpha               = 0.35
selected-background       = "#e5d3cc"
selected-background-alpha = 0.08
selected-text             = "#fa9264"
selected-border           = "hyprland.active-border-foreground"
selected-border-alpha     = 0.25
