--ozone-platform=wayland
--ozone-platform-hint=wayland
--password-store=gnome-libsecret
--enable-features=TouchpadOverscrollHistoryNavigation
--load-extension=/usr/share/omarchy/default/chromium/extensions/copy-url,/home/b47m4n/.local/share/browser-extensions/yt-dlp-chromium,/usr/share/omarchy/default/chromium/extensions/whatsapp-slim,/home/b47m4n/.local/share/browser-extensions/course-pilot
--use-gl=angle
--use-angle=gl
